#Settings for the application

# Number of threads to use for processing wallets
threads: 1

#BY DEFAULT: [0,0] - all wallets
#Example: [2, 6] will run wallets 2,3,4,5,6
#[4,4] will run only wallet 4
range_wallets_to_run: [0,0]

# Whether to shuffle the list of wallets before processing
shuffle_wallets: true

# Working only if range_wallet_to_run = [0,0] 
# BY DEFAULT: [] - all wallets 
# Example: [1, 3, 8] - will run only 1, 3 and 8 wallets
exact_wallets_to_run: []

# Show email in logs
show_email_in_logs: false

#Check for github updates
check_git_updates: true

# the log level for the application. Options: DEBUG, INFO, WARNING, ERROR
log_level : INFO

# get on elevenlabs https://elevenlabs.io/app/sign-in : format key(sk_c1cd37a39fb669ee333cdc9196ce931111122335fa5f2f90)
eleven_labs_api_key : ''

# Api Key from https://dash.capmonster.cloud/
capmonster_api_key: ''

# Show browser 
show_browser: true

# Delay before running the new cicle of wallets after it has completed all actions (1 - 2 hrs default)
random_pause_wallet_after_completion:
  min: 3600
  max: 7200

# Random pause between wallets in seconds
random_pause_between_wallets:
  min: 5
  max: 60

# Random pause between actions in seconds
random_pause_between_actions:
  min: 5
  max: 30

# Random pause to start wallet in seconds
random_pause_start_wallet:
  min: 0
  max: 60

# Min games max games for voice
games:
  min: 7
  max: 15

# Invite Codes for Poseidon, can be used [GQ672VCP]
invite_codes: []

#Use only settings invite codes. If true, only invite codes from the setting above will be applied. If False, random ref codes from both invite_codes and database will be applied.
only_settings_invite_codes: false
